name: kitchensink

services:
  kitchen-sink:
    depends_on:
      - mongo-db
    image: eclipse-temurin:21-jdk-jammy
    container_name: kitchen-sink
    working_dir: /app
    volumes:
      - gradle_cache:/gradle_cache
      - ./gradle:/app/gradle
      - ./src:/app/src
      - ./build.gradle:/app/build.gradle
      - ./gradlew:/app/gradlew
      - ./settings.gradle:/app/settings.gradle
    entrypoint:
      - ./gradlew
    command:
      - bootRun
      - --info
    ports:
      - "8080:8080"
    environment:
      GRADLE_USER_HOME: /gradle_cache
      spring_data_mongodb_host: mongo-db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  mongo-db:
    image: mongo:7.0
    container_name: mongo-db
    hostname: mongo-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: kitchensink
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - mongodb_data:/data/db
    restart: always

  mongo-ui:
    depends_on:
      - mongo-db
    image: mongo-express:1.0
    container_name: mongo-ui
    hostname: mongo-ui
    restart: always
    ports:
      - "8017:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo@mongo-db:27017/
      ME_CONFIG_BASICAUTH: false

networks:
  default:
    name: kitchensink_net

volumes:
  mongodb_data:
    name: kitchensink_mongodb_data
  gradle_cache: