spring:
  application:
    name: kitchensink
  data:
    mongodb:
      host: 192.168.0.204
      password: secret
      username: mongoadmin
      port: 27800
      database: kitchensink
      authentication-database: admin
      auto-index-creation: true