spring:
  data:
    mongodb:
      host: localhost
      password: mongo
      username: mongo
      port: 27017
      database: kitchensink
      authentication-database: admin
      auto-index-creation: true

management:
  endpoint:
    health:
      show-components: always
      show-details: always
  health:
    mongo:
      enabled: true