spring:
  profiles:
    default: local
  application:
    name: kitchensink
  # https://www.baeldung.com/spring-security-oauth-auth-server
  security:
    oauth2:
      authorizationserver:
        client:
          members-client:
            registration:
              client-id: "members-client"
              client-name: "Members"
              client-authentication-methods:
                - "none"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://localhost:8080/login/oauth2/code/members-client-oidc" # Frontend URL
                - "http://localhost:8080/authorized" # Extra Frontend URL if needed
                - "https://oauth.pstmn.io/v1/callback" # For Postman Testing
              post-logout-redirect-uris:
                - "http://localhost:8080/" # Frontend Post Logout URL
              scopes:
                - "openid"
                - "profile"
                - "api:members"
            require-authorization-consent: false
            require-proof-key: true
            token:
              access-token-time-to-live: 3600000
              refresh-token-time-to-live: 18000000
        issuer: http://localhost:8080/
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/

management:
  health:
    mongo:
      enabled: false

logging:
  level:
    root: info
    org:
      springframework:
        security: debug
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
